CREATE TABLE Magazyny (
	ID INTEGER IDENTITY(1,1) PRIMARY KEY,
	Wielkosc INTEGER NOT NULL
)
GO

CREATE TABLE Magazynierzy (
	ID INTEGER IDENTITY(1,1) PRIMARY KEY,
	PESEL CHAR(11),
	Narodowosc VARCHAR(50) NOT NULL,
	ImieNazwisko VARCHAR(50) NOT NULL,
	DataZatrudnienia DATE NOT NULL
)
GO

CREATE TABLE Dostawcy (
	ID INTEGER IDENTITY(1,1) PRIMARY KEY,
	Nazwa VARCHAR(50) NOT NULL,
	Miasto VARCHAR(25) NOT NULL,
	Telefon CHAR(9) NOT NULL,
	DataRozpoczeciaWspolpracy DATE NOT NULL
)
GO

CREATE TABLE Dostawy (
	ID INTEGER IDENTITY(1,1) PRIMARY KEY,
	NumerPrzewozowy VARCHAR(30) NOT NULL,
	DataOdbioru DATE NOT NULL,
	GodzinaOdbioru TIME NOT NULL,
	ID_Dostawcy INTEGER FOREIGN KEY REFERENCES Dostawcy,
	ID_Magazyniera INTEGER FOREIGN KEY REFERENCES Magazynierzy,
	ID_Magazynu INTEGER FOREIGN KEY REFERENCES Magazyny
)
GO

CREATE TABLE Producenci (
	ID INTEGER IDENTITY(1,1) PRIMARY KEY,
	Nazwa VARCHAR(30) NOT NULL,
	Kraj VARCHAR(25) NOT NULL
)
GO

CREATE TABLE Czesci (
	ID INTEGER IDENTITY(1,1) PRIMARY KEY,
	NumerKatalogowy VARCHAR(30) NOT NULL,
	Nazwa VARCHAR(50) NOT NULL,
	StanMagazynowy INTEGER NOT NULL,
	CenaDetaliczna DECIMAL(7,2) NOT NULL,
	Kategoria VARCHAR(50) NOT NULL,
	ID_Magazynu INTEGER FOREIGN KEY REFERENCES Magazyny,
	ID_Producenta INTEGER FOREIGN KEY REFERENCES Producenci
)
GO